# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Netlify deploy
description: Deploy to Netlify
inputs:
  netlify_token:
    description: Netlify personal access token
    required: true
  site_id:
    description: Site ID
    required: true
  build_path:
    description: Build path
    required: false
    default: build
  production:
    description: Boolean string indicating whether to deploy to production
    required: false
    default: "true"
  message:
    description: Message to include in Netlify deploy log
    required: false
    default: Via GitHub
runs:
  using: composite
  steps:
    - uses: notalexross/cicd-github/actions/require-inputs@main
      with:
        every: >
          netlify_token ${{ toJSON(inputs.netlify_token) }}
          site_id ${{ toJSON(inputs.site_id) }}
          build_path ${{ toJSON(inputs.build_path) }}
          production ${{ toJSON(inputs.production) }}
    - shell: bash
      run: |
        npm i -g netlify-cli@9
        netlify deploy \
          --dir "${{ inputs.build_path }}" \
          --message "${{ inputs.message }}" \
          --timeout 600 \
          $([[ "${{ inputs.production }}" == true ]] && echo --prod) \
          | perl -pe "s|http(s)?.*?(\h\|$)|***\2|"
      env:
        NETLIFY_SITE_ID: ${{ inputs.site_id }}
        NETLIFY_AUTH_TOKEN: ${{ inputs.netlify_token }}
