# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Run if present
description: Run an NPM script if present in package.json
inputs:
  script:
    description: NPM script
    required: true
  env:
    description: Environment variables
    required: false
  error_level:
    description: Error level, i.e. off/warn/error
    required: false
    default: warn
outputs:
  outcome:
    description: Run outcome, i.e. success, failure, cancelled, or skipped
    value: ${{ steps.run.outcome }}
runs:
  using: composite
  steps:
    - uses: notalexross/cicd-github/actions/require-inputs@main
      with:
        every: >
          script ${{ toJSON(inputs.script) }}
          error_level ${{ toJSON(inputs.error_level) }}
    - if: ${{ !contains(fromJson('["off", "warn", "error"]'), inputs.error_level) }}
      shell: bash
      run: |
        echo "::error::error_level must be one of: off, warn, error."
        exit 11
    - id: get_script_name
      shell: bash
      run: |
        script="${{ inputs.script }}"
        name=${script%% *}
        echo "::set-output name=name::${name}"
    - id: check_if_present
      shell: bash
      run: |
        if npm run | grep -qx "  ${{ steps.get_script_name.outputs.name }}"; then
          echo "::set-output name=present::true"
        else
          echo "::set-output name=present::false"
          if [[ ${{ inputs.error_level }} == "warn" ]]; then
            echo "::warning::Skipping missing script: \"${{ steps.get_script_name.outputs.name }}\"."
          elif [[ ${{ inputs.error_level }} == "error" ]]; then
            echo "::error::Missing script: \"${{ steps.get_script_name.outputs.name }}\"."
            exit 11
          fi
        fi
    - id: run
      if: ${{ steps.check_if_present.outputs.present == 'true' }}
      shell: bash
      run: |
        set -o allexport
        ${{ inputs.env }}
        set +o allexport
        npm run ${{ inputs.script }}
